DROP TABLE IF EXISTS friendships CASCADE;
CREATE TABLE friendships (
  id SERIAL PRIMARY KEY NOT NULL,
  senderId INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  recieverId INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE
);